import React, { useState, useEffect, useCallback } from 'react';
import { type AIDailyBrief } from '../../types/ai.ts';
import { AIService } from '../../services/ai.service.ts';
import { Modal } from '../common/Modal.tsx';
import { Button } from '../common/Button.tsx';
import { UrsellaSymbolMark } from '../common/UrsellaLogo.tsx';
import { useTheme } from '../../contexts/ThemeContext.tsx';
import {
  Sparkles,
  Package,
  Users,
  Copy,
  Check,
  RefreshCw,
  ArrowRight,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react';

interface DailyBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  businessId: string;
  businessName: string;
  currency: string;
  onAskFollowUp?: (prompt: string) => void;
}

export const DailyBriefModal: React.FC<DailyBriefModalProps> = ({
  isOpen,
  onClose,
  businessId,
  businessName,
  currency,
  onAskFollowUp,
}) => {
  const { isDark } = useTheme();
  const [brief, setBrief] = useState<AIDailyBrief | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  const fetchBrief = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const data = await AIService.fetchDailyBrief(businessId || '', {
        businessName: businessName || 'My Business',
        currency: currency || 'XAF',
      });
      setBrief(data);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to generate daily brief.';
      setError(msg);
    } finally {
      setLoading(false);
    }
  }, [businessId, businessName, currency]);

  useEffect(() => {
    if (isOpen) {
      fetchBrief();
    }
  }, [isOpen, fetchBrief]);

  const handleCopyText = () => {
    if (!brief) return;
    const rev = Number(brief.performanceSnapshot?.revenue || 0).toLocaleString();
    const trans = brief.performanceSnapshot?.transactions || 0;
    const collected = Number(brief.performanceSnapshot?.amountCollected || 0).toLocaleString();
    const exp = Number(brief.performanceSnapshot?.expenses || 0).toLocaleString();
    const debt = Number(brief.performanceSnapshot?.outstandingReceivables || 0).toLocaleString();

    const text = `DAILY BUSINESS BRIEF - ${brief.businessName || businessName}
${brief.headline || 'Daily Performance Report'}

EXECUTIVE SUMMARY:
${brief.executiveSummary || 'Ready for operations.'}

PERFORMANCE SNAPSHOT:
- Revenue Today: ${currency} ${rev} (${trans} orders)
- Cash Collected: ${currency} ${collected}
- Operating Expenses: ${currency} ${exp}
- Total Receivables: ${currency} ${debt}

RECOMMENDED FOCUS TODAY:
${brief.recommendedFocusToday || 'Process transactions and monitor stock levels.'}

Generated by Ursella AI on ${new Date(brief.generatedAt || Date.now()).toLocaleString()}`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const revenue = Number(brief?.performanceSnapshot?.revenue || 0);
  const transactions = Number(brief?.performanceSnapshot?.transactions || 0);
  const amountCollected = Number(brief?.performanceSnapshot?.amountCollected || 0);
  const expenses = Number(brief?.performanceSnapshot?.expenses || 0);
  const outstandingReceivables = Number(brief?.performanceSnapshot?.outstandingReceivables || 0);

  const inventoryAlerts = Array.isArray(brief?.inventoryAlerts) ? brief.inventoryAlerts : [];
  const debtFollowUps = Array.isArray(brief?.debtFollowUps) ? brief.debtFollowUps : [];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Daily Business Brief"
      maxWidth="xl"
    >
      <div className="space-y-4 sm:space-y-5">
        {/* Header Ribbon */}
        <div className={`flex items-center justify-between p-3.5 rounded-xl border ${
          isDark 
            ? 'bg-gradient-to-r from-indigo-950/40 via-zinc-900 to-zinc-900 border-indigo-500/30' 
            : 'bg-gradient-to-r from-indigo-50 via-slate-50 to-emerald-50 border-indigo-200'
        }`}>
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl border flex items-center justify-center shrink-0 shadow-xs ${
              isDark ? 'bg-zinc-900 border-indigo-500/30' : 'bg-white border-indigo-200'
            }`}>
              <UrsellaSymbolMark sizeClass="w-5 h-5" theme="ai" />
            </div>
            <div>
              <div className={`text-sm font-bold flex items-center gap-2 ${isDark ? 'text-white' : 'text-slate-900'}`}>
                <span>{businessName || 'Business'} Daily Briefing</span>
                <span className={`text-[10px] font-mono px-2 py-0.5 rounded-full ${
                  isDark ? 'bg-zinc-800 text-zinc-300' : 'bg-slate-200 text-slate-700 font-semibold'
                }`}>
                  {new Date().toLocaleDateString(undefined, {
                    weekday: 'short',
                    month: 'short',
                    day: 'numeric',
                  })}
                </span>
              </div>
              <div className={`text-xs ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Powered by Ursella Intelligence Engine</div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={fetchBrief}
              disabled={loading}
              className={`p-2 rounded-xl border transition-colors disabled:opacity-50 ${
                isDark 
                  ? 'bg-zinc-800/80 hover:bg-zinc-700 text-zinc-300 border-zinc-700/60' 
                  : 'bg-white hover:bg-slate-100 text-slate-700 border-slate-200 shadow-xs'
              }`}
              title="Refresh Briefing"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <button
              onClick={handleCopyText}
              disabled={!brief}
              className={`p-2 rounded-xl border transition-colors disabled:opacity-50 ${
                isDark 
                  ? 'bg-zinc-800/80 hover:bg-zinc-700 text-zinc-300 border-zinc-700/60' 
                  : 'bg-white hover:bg-slate-100 text-slate-700 border-slate-200 shadow-xs'
              }`}
              title="Copy text brief"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="py-12 text-center space-y-3">
            <div className={`inline-flex p-3 rounded-2xl border shadow-lg ${
              isDark ? 'bg-zinc-900 border-indigo-500/30 shadow-indigo-950/30' : 'bg-white border-indigo-200 shadow-indigo-100'
            }`}>
              <UrsellaSymbolMark sizeClass="w-8 h-8" theme="ai" isAnimated={true} />
            </div>
            <div className={`text-sm font-semibold ${isDark ? 'text-white' : 'text-slate-900'}`}>Synthesizing Today's Business Facts...</div>
            <div className={`text-xs max-w-sm mx-auto ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
              Analyzing daily sales, customer balances, and inventory thresholds to formulate your briefing.
            </div>
          </div>
        )}

        {/* Error State */}
        {error && !loading && (
          <div className={`p-4 rounded-xl border text-sm flex items-center justify-between ${
            isDark ? 'bg-rose-950/30 border-rose-500/30 text-rose-300' : 'bg-rose-50 border-rose-200 text-rose-700'
          }`}>
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0 text-rose-500" />
              <span>{error}</span>
            </div>
            <Button size="sm" variant="secondary" onClick={fetchBrief}>
              Retry
            </Button>
          </div>
        )}

        {/* Content State */}
        {brief && !loading && (
          <div className="space-y-4">
            {/* Headline Card */}
            <div className={`p-4 rounded-xl border space-y-2 ${
              isDark ? 'bg-zinc-900/90 border-zinc-800' : 'bg-slate-50 border-slate-200'
            }`}>
              <div className={`text-sm font-bold leading-snug ${isDark ? 'text-white' : 'text-slate-900'}`}>
                {brief.headline || `Daily Briefing for ${businessName}`}
              </div>
              <p className={`text-xs leading-relaxed ${isDark ? 'text-zinc-300' : 'text-slate-600'}`}>
                {brief.executiveSummary || 'Daily operations summary ready.'}
              </p>
            </div>

            {/* Performance Grid */}
            <div>
              <div className={`text-[11px] font-semibold uppercase tracking-wider mb-2 ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
                Today's Snapshot
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                <div className={`p-3 rounded-xl border ${
                  isDark ? 'bg-zinc-950/80 border-zinc-800' : 'bg-white border-slate-200 shadow-xs'
                }`}>
                  <div className={`text-[10px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Revenue Today</div>
                  <div className="text-sm font-bold text-emerald-500 mt-0.5">
                    {currency} {revenue.toLocaleString()}
                  </div>
                  <div className={`text-[10px] mt-0.5 ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>
                    {transactions} orders
                  </div>
                </div>

                <div className={`p-3 rounded-xl border ${
                  isDark ? 'bg-zinc-950/80 border-zinc-800' : 'bg-white border-slate-200 shadow-xs'
                }`}>
                  <div className={`text-[10px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Cash Collected</div>
                  <div className={`text-sm font-bold mt-0.5 ${isDark ? 'text-white' : 'text-slate-900'}`}>
                    {currency} {amountCollected.toLocaleString()}
                  </div>
                  <div className={`text-[10px] mt-0.5 ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>Receipts in hand</div>
                </div>

                <div className={`p-3 rounded-xl border ${
                  isDark ? 'bg-zinc-950/80 border-zinc-800' : 'bg-white border-slate-200 shadow-xs'
                }`}>
                  <div className={`text-[10px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Expenses Today</div>
                  <div className="text-sm font-bold text-rose-500 mt-0.5">
                    {currency} {expenses.toLocaleString()}
                  </div>
                  <div className={`text-[10px] mt-0.5 ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>Outflows logged</div>
                </div>

                <div className={`p-3 rounded-xl border ${
                  isDark ? 'bg-zinc-950/80 border-zinc-800' : 'bg-white border-slate-200 shadow-xs'
                }`}>
                  <div className={`text-[10px] ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>Outstanding Debt</div>
                  <div className="text-sm font-bold text-amber-500 mt-0.5">
                    {currency} {outstandingReceivables.toLocaleString()}
                  </div>
                  <div className={`text-[10px] mt-0.5 ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>Total credit owed</div>
                </div>
              </div>
            </div>

            {/* Strategic Focus Today */}
            <div className={`p-3.5 rounded-xl border space-y-1 ${
              isDark 
                ? 'bg-gradient-to-r from-amber-500/10 to-zinc-900 border-amber-500/30' 
                : 'bg-amber-50 border-amber-200'
            }`}>
              <div className="text-[10px] font-bold uppercase tracking-wider text-amber-600 dark:text-amber-400 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />
                Recommended Focus Today
              </div>
              <div className={`text-xs font-semibold ${isDark ? 'text-zinc-100' : 'text-slate-800'}`}>
                {brief.recommendedFocusToday || 'Review inventory velocity and counter sales.'}
              </div>
            </div>

            {/* Alerts & Followups */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {/* Inventory Alert */}
              <div className={`p-3 rounded-xl border space-y-1.5 ${
                isDark ? 'bg-zinc-950/60 border-zinc-800' : 'bg-slate-50 border-slate-200'
              }`}>
                <div className={`text-[11px] font-semibold flex items-center gap-1.5 ${isDark ? 'text-zinc-300' : 'text-slate-700'}`}>
                  <Package className="w-3.5 h-3.5 text-blue-500" />
                  Inventory Priorities
                </div>
                {inventoryAlerts.length > 0 ? (
                  <ul className={`text-xs space-y-1 ${isDark ? 'text-zinc-400' : 'text-slate-600'}`}>
                    {inventoryAlerts.map((alert, i) => (
                      <li key={i} className="flex items-start gap-1.5">
                        <span className="text-blue-500">•</span>
                        <span>{alert}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className={`text-xs italic ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>
                    All inventory levels are healthy.
                  </p>
                )}
              </div>

              {/* Debt Followups */}
              <div className={`p-3 rounded-xl border space-y-1.5 ${
                isDark ? 'bg-zinc-950/60 border-zinc-800' : 'bg-slate-50 border-slate-200'
              }`}>
                <div className={`text-[11px] font-semibold flex items-center gap-1.5 ${isDark ? 'text-zinc-300' : 'text-slate-700'}`}>
                  <Users className="w-3.5 h-3.5 text-rose-500" />
                  Debtor Follow-ups
                </div>
                {debtFollowUps.length > 0 ? (
                  <ul className={`text-xs space-y-1 ${isDark ? 'text-zinc-400' : 'text-slate-600'}`}>
                    {debtFollowUps.map((item, i) => (
                      <li key={i} className="flex items-start gap-1.5">
                        <span className="text-rose-500">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                ) : (
                  <p className={`text-xs italic ${isDark ? 'text-zinc-500' : 'text-slate-400'}`}>
                    No overdue debtor accounts flagged.
                  </p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Modal Footer */}
        <div className={`flex flex-col sm:flex-row items-center justify-between gap-3 pt-3 border-t ${
          isDark ? 'border-zinc-800' : 'border-slate-200'
        }`}>
          <div className={`text-[11px] flex items-center gap-1 ${isDark ? 'text-zinc-400' : 'text-slate-500'}`}>
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" />
            <span>Factual grounding in transactional records</span>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            {onAskFollowUp && brief && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  onClose();
                  onAskFollowUp('How do today sales compare to yesterday and last week?');
                }}
                className="w-full sm:w-auto"
              >
                <span>Ask Ursella</span>
                <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
              </Button>
            )}
            <Button variant="primary" size="sm" onClick={onClose} className="w-full sm:w-auto">
              Close Briefing
            </Button>
          </div>
        </div>
      </div>
    </Modal>
  );
};
