import React, { useState, useEffect } from 'react';
import { type AIDailyBrief } from '../../types/ai.ts';
import { AIService } from '../../services/ai.service.ts';
import { Modal } from '../common/Modal.tsx';
import { Button } from '../common/Button.tsx';
import {
  Sun,
  Sparkles,
  TrendingUp,
  Package,
  Users,
  Copy,
  Check,
  RefreshCw,
  ArrowRight,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react';

interface DailyBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  businessId: string;
  businessName: string;
  currency: string;
  onAskFollowUp?: (prompt: string) => void;
}

export const DailyBriefModal: React.FC<DailyBriefModalProps> = ({
  isOpen,
  onClose,
  businessId,
  businessName,
  currency,
  onAskFollowUp,
}) => {
  const [brief, setBrief] = useState<AIDailyBrief | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  const fetchBrief = async () => {
    if (!businessId) return;
    try {
      setLoading(true);
      setError(null);
      const data = await AIService.fetchDailyBrief(businessId, {
        businessName,
        currency,
      });
      setBrief(data);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to generate daily brief.';
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen && !brief) {
      fetchBrief();
    }
  }, [isOpen, businessId]);

  const handleCopyText = () => {
    if (!brief) return;
    const text = `DAILY BUSINESS BRIEF - ${brief.businessName}
${brief.headline}

EXECUTIVE SUMMARY:
${brief.executiveSummary}

PERFORMANCE SNAPSHOT:
- Revenue Today: ${currency} ${brief.performanceSnapshot.revenue.toLocaleString()} (${brief.performanceSnapshot.transactions} orders)
- Cash Collected: ${currency} ${brief.performanceSnapshot.amountCollected.toLocaleString()}
- Operating Expenses: ${currency} ${brief.performanceSnapshot.expenses.toLocaleString()}
- Total Receivables: ${currency} ${brief.performanceSnapshot.outstandingReceivables.toLocaleString()}

RECOMMENDED FOCUS TODAY:
${brief.recommendedFocusToday}

Generated by ursella ai on ${new Date(brief.generatedAt).toLocaleString()}`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Daily Business Brief"
      maxWidth="xl"
    >
      <div className="space-y-5">
        {/* Header Ribbon */}
        <div className="flex items-center justify-between p-3.5 rounded-xl bg-gradient-to-r from-amber-500/15 via-amber-500/5 to-zinc-900 border border-amber-500/30">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400">
              <Sun className="w-5 h-5" />
            </div>
            <div>
              <div className="text-sm font-bold text-white flex items-center gap-2">
                <span>{businessName} Daily Briefing</span>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-zinc-800 text-zinc-300">
                  {new Date().toLocaleDateString(undefined, {
                    weekday: 'short',
                    month: 'short',
                    day: 'numeric',
                  })}
                </span>
              </div>
              <div className="text-xs text-zinc-400">Powered by Ursella AI Intelligence</div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={fetchBrief}
              disabled={loading}
              className="p-2 rounded-xl bg-zinc-800/80 hover:bg-zinc-700 text-zinc-300 transition-colors disabled:opacity-50"
              title="Refresh Briefing"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </button>
            <button
              onClick={handleCopyText}
              disabled={!brief}
              className="p-2 rounded-xl bg-zinc-800/80 hover:bg-zinc-700 text-zinc-300 transition-colors disabled:opacity-50"
              title="Copy text brief"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </div>

        {/* Loading State */}
        {loading && (
          <div className="py-12 text-center space-y-3">
            <div className="inline-flex p-3 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 animate-pulse">
              <Sparkles className="w-6 h-6 animate-spin" />
            </div>
            <div className="text-sm font-semibold text-white">Synthesizing Today's Business Facts...</div>
            <div className="text-xs text-zinc-400 max-w-sm mx-auto">
              Analyzing daily sales, customer balances, and inventory thresholds to formulate your briefing.
            </div>
          </div>
        )}

        {/* Error State */}
        {error && !loading && (
          <div className="p-4 rounded-xl bg-rose-950/30 border border-rose-500/30 text-rose-300 text-sm flex items-center justify-between">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
            <Button size="sm" variant="secondary" onClick={fetchBrief}>
              Retry
            </Button>
          </div>
        )}

        {/* Content State */}
        {brief && !loading && (
          <div className="space-y-4">
            {/* Headline Card */}
            <div className="p-4 rounded-xl bg-zinc-900 border border-zinc-800 space-y-2">
              <div className="text-sm font-bold text-white leading-snug">{brief.headline}</div>
              <p className="text-xs text-zinc-300 leading-relaxed">{brief.executiveSummary}</p>
            </div>

            {/* Performance Grid */}
            <div>
              <div className="text-[11px] font-semibold uppercase tracking-wider text-zinc-400 mb-2">
                Today's Snapshot
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                <div className="p-3 rounded-xl bg-zinc-950/80 border border-zinc-800">
                  <div className="text-[10px] text-zinc-400">Revenue Today</div>
                  <div className="text-sm font-bold text-emerald-400 mt-0.5">
                    {currency} {brief.performanceSnapshot.revenue.toLocaleString()}
                  </div>
                  <div className="text-[10px] text-zinc-400 mt-0.5">
                    {brief.performanceSnapshot.transactions} orders
                  </div>
                </div>

                <div className="p-3 rounded-xl bg-zinc-950/80 border border-zinc-800">
                  <div className="text-[10px] text-zinc-400">Cash Collected</div>
                  <div className="text-sm font-bold text-white mt-0.5">
                    {currency} {brief.performanceSnapshot.amountCollected.toLocaleString()}
                  </div>
                  <div className="text-[10px] text-zinc-400 mt-0.5">Receipts in hand</div>
                </div>

                <div className="p-3 rounded-xl bg-zinc-950/80 border border-zinc-800">
                  <div className="text-[10px] text-zinc-400">Expenses Today</div>
                  <div className="text-sm font-bold text-rose-400 mt-0.5">
                    {currency} {brief.performanceSnapshot.expenses.toLocaleString()}
                  </div>
                  <div className="text-[10px] text-zinc-400 mt-0.5">Outflows logged</div>
                </div>

                <div className="p-3 rounded-xl bg-zinc-950/80 border border-zinc-800">
                  <div className="text-[10px] text-zinc-400">Outstanding Debt</div>
                  <div className="text-sm font-bold text-amber-400 mt-0.5">
                    {currency} {brief.performanceSnapshot.outstandingReceivables.toLocaleString()}
                  </div>
                  <div className="text-[10px] text-zinc-400 mt-0.5">Total credit owed</div>
                </div>
              </div>
            </div>

            {/* Strategic Focus Today */}
            <div className="p-3.5 rounded-xl bg-gradient-to-r from-amber-500/10 to-zinc-900 border border-amber-500/30 space-y-1">
              <div className="text-[10px] font-bold uppercase tracking-wider text-amber-400 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />
                Recommended Focus Today
              </div>
              <div className="text-xs font-semibold text-zinc-100">
                {brief.recommendedFocusToday}
              </div>
            </div>

            {/* Alerts & Followups */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {/* Inventory Alert */}
              <div className="p-3 rounded-xl bg-zinc-950/60 border border-zinc-800 space-y-1.5">
                <div className="text-[11px] font-semibold text-zinc-300 flex items-center gap-1.5">
                  <Package className="w-3.5 h-3.5 text-blue-400" />
                  Inventory Priorities
                </div>
                <ul className="text-xs text-zinc-400 space-y-1">
                  {brief.inventoryAlerts.map((alert, i) => (
                    <li key={i} className="flex items-start gap-1.5">
                      <span className="text-zinc-400">•</span>
                      <span>{alert}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Debt Followups */}
              <div className="p-3 rounded-xl bg-zinc-950/60 border border-zinc-800 space-y-1.5">
                <div className="text-[11px] font-semibold text-zinc-300 flex items-center gap-1.5">
                  <Users className="w-3.5 h-3.5 text-rose-400" />
                  Debtor Follow-ups
                </div>
                <ul className="text-xs text-zinc-400 space-y-1">
                  {brief.debtFollowUps.map((item, i) => (
                    <li key={i} className="flex items-start gap-1.5">
                      <span className="text-zinc-400">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* Modal Footer */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-3 border-t border-zinc-800">
          <div className="text-[11px] text-zinc-400 flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
            <span>Factual grounding in transactional records</span>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            {onAskFollowUp && brief && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  onClose();
                  onAskFollowUp('How do today sales compare to yesterday and last week?');
                }}
                className="w-full sm:w-auto"
              >
                <span>Ask Ursella</span>
                <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
              </Button>
            )}
            <Button variant="primary" size="sm" onClick={onClose} className="w-full sm:w-auto">
              Close Briefing
            </Button>
          </div>
        </div>
      </div>
    </Modal>
  );
};
